export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTERATION_REQUEST = "REGISTERATION_REQUEST";
export const REGISTERATION_SUCCESS = "REGISTERATION_SUCCESS";
export const REGISTERATION_FAIL = "REGISTERATION_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
