export const REGISTER_DEVICE_REQUEST = "REGISTER_DEVICE_REQUEST";
export const REGISTER_DEVICE_SUCCESS = "REGISTER_DEVICE_SUCCESS";
export const REGISTER_DEVICE_FAIL = "REGISTER_DEVICE_FAIL";
export const REGISTER_DEVICE_RESET = "REGISTER_DEVICE_RESET";

export const GET_REGISTERED_DEVICE_REQUEST = "GET_REGISTERED_DEVICE_REQUEST";
export const GET_REGISTERED_DEVICE_SUCCESS = "GET_REGISTERED_DEVICE_SUCCESS";
export const GET_REGISTERED_DEVICE_FAIL = "GET_REGISTERED_DEVICE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
