export const REGISTER_DEVICE_REQUEST = "REGISTER_DEVICE_REQUEST";
export const REGISTER_DEVICE_SUCCESS = "REGISTER_DEVICE_SUCCESS";
export const REGISTER_DEVICE_FAIL = "REGISTER_DEVICE_FAIL";
export const REGISTER_DEVICE_RESET = "REGISTER_DEVICE_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
