export const REPORT_DEVICE_REQUEST = "REPORT_DEVICE_REQUEST";
export const REPORT_DEVICE_SUCCESS = "REPORT_DEVICE_SUCCESS";
export const REPORT_DEVICE_FAIL = "REPORT_DEVICE_FAIL";
export const REPORT_DEVICE_RESET = "REPORT_DEVICE_RESET";

export const ALL_REPORTED_DEVICES_REQUEST = "ALL_REPORTED_DEVICES_REQUEST";
export const ALL_REPORTED_DEVICES_SUCCESS = "ALL_REPORTED_DEVICES_SUCCESS";
export const ALL_REPORTED_DEVICES_FAIL = "ALL_REPORTED_DEVICES_FAIL";

export const REPORTED_DEVICE_DETAILS_REQUEST =
  "REPORTED_DEVICE_DETAILS_REQUEST";
export const REPORTED_DEVICE_DETAILS_SUCCESS =
  "REPORTED_DEVICE_DETAILS_SUCCESS";
export const REPORTED_DEVICE_DETAILS_FAIL = "REPORTED_DEVICE_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
