export const REPORT_DEVICE_REQUEST = "REPORT_DEVICE_REQUEST";
export const REPORT_DEVICE_SUCCESS = "REPORT_DEVICE_SUCCESS";
export const REPORT_DEVICE_FAIL = "REPORT_DEVICE_FAIL";
export const REPORT_DEVICE_RESET = "REPORT_DEVICE_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
